### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by neuromancer** [CallumDev/Librelancer#2]
It is not clear in the README if Linux currently supported or not. Do you need people to test it?

**Comment by CallumDev** [comment]
I've tested it on AMD proprietary and it works there. When I last had an nVidia card, however, it did not work. Therefore I am not officially advertising Linux support, though if you have an nVidia card and can test that'd be grand.

**Comment by neuromancer** [comment]
Great. I asked the people from [/r/linux_gaming](https://www.reddit.com/r/linux_gaming/comments/4kiv5d/librelancer_an_open_source_reimplementation_of/) to test your code. Hopefully you will have some interesting bug reports soon..

**Comment by vitorhnn** [comment]
It's working with the 364.19 proprietary drivers.
![screenshot](https://i.imgur.com/dB7uR4Z.png)

**Comment by Temeez** [comment]
@vitorhnn how did you get it working on Linux? I managed to build it, but now when it asks for the Freelancer dir and I give it one, it says its not a valid freelancer directory.

**Comment by CallumDev** [comment]
@Temeez make sure you've selected the Freelancer directory, and not the EXE or DATA directories

**Comment by Temeez** [comment]
Yesh, works well with 364.19 proprietary drivers on Arch Linux.
![librelancer](https://cloud.githubusercontent.com/assets/3135774/15462890/55864832-20ce-11e6-8b8d-cc8b6d9eea10.png)

**Comment by CallumDev** [comment]
README updated, Linux support seems to be working fine. Please file another issue if there's a Linux-specific incompatibility :)
