### ISSUE TITLE
[Feature Request] Language Support

### ISSUE THREAD

**Issue by aphirst** [CallumDev/Librelancer#6]
I'm fully aware that this is likely to be out of scope for a long while, but it would be nice to be sure that the different (non-English) versions of the game can also be imported, and run correctly (which probably only pertains to making sure that special characters are handled).

**Comment by CallumDev** [comment]
I don't have a non-English version of Freelancer to test out, but for latin script languages the font renderer should work correctly. The only thing not implemented is falling back when glyphs aren't available. Furthermore, all the text handling code is written to be Unicode-aware. If you can comment with screenshots of the current non-English behaviour for various versions that'd be great.

**Comment by aphirst** [comment]
I'll do that just as soon as I can get Librelancer built and running on my own machine (I tried earlier and failed, but haven't had time yet to thoroughly investigate). I have the English and German versions, but I know there's also a Russian version that might be of interest to some people. Maybe I can get hold of it from someone...

**Comment by CallumDev** [comment]
The game can technically render special characters now. There may need to be lang-specific infocard work in future but for now this can be closed.
